apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-fzjd
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0030-tenant/tkrw-pr714-0075-0030-app/devfile-sample-fzjd@sha256:c0d430bec1de0ff6b4603cd3112a021146601d6c17eab7ca198cb1594be90b13
        name: my-nodejs
        resources: {}
status: {}
